### ISSUE TITLE
Flyover Flight-Vision Pipeline

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#17]
# Flyover Flight-Vision Pipeline

## Problem

Need ability for flight and vision to communicate during the airdrop flyover phase of the competition.

## Solution

Need pipeline object that will run vision code on images taken during the airdrop flyover and return results to flight infrastructure.

## Additional Information

This pipeline will run standard and emergent object algorithms in order to determine the locations of the standard and emergent objects.

**Comment by cjhr95** [comment]
Since the old pipeline code is so garbo, I've been looking at other solutions:
We discussed the common file method where vision would write data to a JSON, and flight would read it. 
There's also some built-in functionality with Python Multiprocessing, the SharedMemory class. Each instance of a SharedMemory list would be a standard object, and these lists can be accessed between processes. SharedMemory lists support int, float, bool, str, byte, and None types.

Python Documentation: https://docs.python.org/3/library/multiprocessing.shared_memory.html#multiprocessing.managers.SharedMemoryManager.ShareableList

**Comment by fallscameron01** [comment]
Updated to be specific to the airdrop flyover phase of the competition. Essentially, there will be 3 separate flight-vision pipelines:
- Flyover (standard and emergent objects)
- Air drop (judge detection)
- LiDAR (obstacle detection)
