### ISSUE TITLE
Encrypt connection to drone

### ISSUE THREAD

**Issue by fallscameron01** [MissouriMRR/SUAS-2023#28]
# Encrypt connection to drone

## Problem

In order to prevent problems at competition with other teams sending signals on the same channels, encrypt/sign the connection to the drone.

## Solution

This can probably be achieved through MavSDK's functionality, although the assignee will have to do research to figure it out.

## Additional Resources

- mavlink message signing: https://mavlink.io/en/guide/message_signing.html

**Comment by DJDMVP** [comment]
With encryption there is no reason to encrypt our code going to the drone from the base station because before connection encryption can't be used and once connected encryption is useless because that would just be preventing our information from getting stolen from others which doesn't really matter. The goal would be to prevent other signals from connecting to our drone. With connecting to our drone, I don't think the drone can have two connections to two different base stations (nothing can be found confirming or denying), so once our base station connects to the drone there shouldn't be a problem with external connections to our drone. This is all we could find about connections and it only talks about a base station connecting to two drones and not the other way, [https://mavsdk.mavlink.io/main/en/cpp/guide/connections.html](url).

**Comment by fallscameron01** [comment]
Not an issue. Any malicious action that this would prevent would require a lot of effort and be against competition rules, so this is not a concern.
